openapi: 3.1.0
info:
  title: Bank Feeds Account mapping Data integrity API
  version: 3.0.0
  contact:
    email: support@codat.io
    name: Codat
  description: 'Bank Feeds solution enables your SMB users to set up bank feeds from accounts in your application to supported accounting software.


    A bank feed is a connection between a source bank account in your application and a target bank account in a supported accounting software.


    [Explore solution](https://docs.codat.io/bank-feeds-api/overview) | [See OpenAPI spec](https://github.com/codatio/oas)


    ---

    <!-- Start Codat Tags Table -->

    ## Endpoints


    | Endpoints | Description |

    | :- |:- |

    | Companies | Create and manage your SMB users'' companies. |

    | Connections | Create new and manage existing data connections for a company. |

    | Source accounts | Provide and manage lists of source bank accounts. |

    | Account mapping | Extra functionality for building an account management UI. |

    | Company information | Get detailed information about a company from the underlying platform. |

    | Transactions | Create new bank account transactions for a company''s connections, and see previous operations. |

    <!-- End Codat Tags Table -->'
  termsOfService: https://www.codat.io/legals/
servers:
- description: Production
  url: https://api.codat.io
security:
- auth_header: []
tags:
- name: Data integrity
  description: Match mutable accounting data with immutable banking data to increase confidence in financial data.
paths:
  /data/companies/{companyId}/assess/dataTypes/{dataType}/dataIntegrity/status:
    parameters:
    - $ref: '#/components/parameters/companyId'
    - $ref: '#/components/parameters/dataIntegrityDataType'
    get:
      summary: Get data integrity status
      tags:
      - Data integrity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataIntegrityStatuses'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '402':
          $ref: '#/components/responses/Payment-Required'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/Not-Found'
        '429':
          $ref: '#/components/responses/Too-Many-Requests'
        '500':
          $ref: '#/components/responses/Internal-Server-Error'
        '503':
          $ref: '#/components/responses/Service-Unavailable'
      operationId: get-data-integrity-status
      x-speakeasy-name-override: status
      description: 'The *Get data integrity status* endpoint returns the [status](https://docs.codat.io/lending-api#/schemas/DataIntegrityStatus) for the company’s match results between the data type provided in the URL and other data types that Data Integrity uses to support matching.

        This endpoint helps you understand whether match data is available and, if so, how to usefully query it.


        The response tells you:


        - Whether match results are available.

        - When the results were generated, and their status.

        - The connection IDs, amounts, and dates involved to support useful querying.'
  /data/companies/{companyId}/assess/dataTypes/{dataType}/dataIntegrity/summaries:
    parameters:
    - $ref: '#/components/parameters/companyId'
    - $ref: '#/components/parameters/dataIntegrityDataType'
    get:
      summary: Get data integrity summaries
      tags:
      - Data integrity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataIntegritySummaries'
        '400':
          $ref: '#/components/responses/Malformed-Query'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '402':
          $ref: '#/components/responses/Payment-Required'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/Not-Found'
        '429':
          $ref: '#/components/responses/Too-Many-Requests'
        '500':
          $ref: '#/components/responses/Internal-Server-Error'
        '503':
          $ref: '#/components/responses/Service-Unavailable'
      operationId: get-data-integrity-summaries
      x-speakeasy-name-override: summaries
      description: "The *Get data integrity summary* endpoint returns a [summary](https://docs.codat.io/lending-api#/schemas/DataIntegritySummary) of match results for a given data type filtered by a query string in the [Codat query language](https://docs.codat.io/using-the-api/querying). \n\nFor example, if you wanted to see summary match results only for transactions after 1 December 2020, you could include a query parameter of `query=date>2020-12-01`.\n\nThe endpoint response includes only the summary results, not transactions. To view match data for transactions, use the [List data integrity details](https://docs.codat.io/lending-api#/operations/get-data-integrity-summaries) endpoint."
      parameters:
      - $ref: '#/components/parameters/query'
  /data/companies/{companyId}/assess/dataTypes/{dataType}/dataIntegrity/details:
    parameters:
    - $ref: '#/components/parameters/companyId'
    - $ref: '#/components/parameters/dataIntegrityDataType'
    get:
      summary: List data integrity details
      tags:
      - Data integrity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataIntegrityDetails'
              examples: {}
        '400':
          $ref: '#/components/responses/Malformed-Query'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '402':
          $ref: '#/components/responses/Payment-Required'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/Not-Found'
        '429':
          $ref: '#/components/responses/Too-Many-Requests'
        '500':
          $ref: '#/components/responses/Internal-Server-Error'
        '503':
          $ref: '#/components/responses/Service-Unavailable'
      operationId: list-data-integrity-details
      x-speakeasy-name-override: details
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/orderBy'
      description: 'The *List data integrity details* endpoint returns the match result record by record for a given data type, filtered based on a query string in the same way as summary results.


        The [details](https://docs.codat.io/lending-api#/schemas/DataIntegrityDetail) are paginated and support ordering, following the same conventions as our other data endpoints.'
components:
  schemas:
    DataIntegrityStatus:
      title: Data integrity status
      type: object
      allOf:
      - $ref: '#/components/schemas/DataIntegritySummary/definitions/dataIntegrityType'
      - type: object
        properties:
          statusInfo:
            $ref: '#/components/schemas/DataIntegrityStatus/definitions/dataIntegrityStatusInfo'
          connectionIds:
            $ref: '#/components/schemas/DataIntegrityStatus/definitions/dataIntegrityConnectionId'
          amounts:
            $ref: '#/components/schemas/DataIntegrityStatus/definitions/dataIntegrityAmounts'
          dates:
            $ref: '#/components/schemas/DataIntegrityStatus/definitions/dataIntegrityDates'
      definitions:
        dataIntegrityStatusInfo:
          type: object
          properties:
            lastMatched:
              type: string
              $ref: '#/components/schemas/DateTime'
              description: The date the matching algorithm last ran against the company’s data type specified.
              readOnly: true
            currentStatus:
              $ref: '#/components/schemas/DataIntegrityStatus/definitions/integrityStatus'
            statusMessage:
              type: string
              description: Detailed explanation supporting the status value.
        dataIntegrityConnectionId:
          type: object
          properties:
            source:
              type: array
              description: An array of strings. The connection IDs for the type specified in the url.
              items:
                type: string
            target:
              type: array
              description: An array of strings. The connection IDs for the type being matched to.
              items:
                type: string
        dataIntegrityAmounts:
          type: object
          description: Only returned for transactions. For accounts, there is nothing returned.
          properties:
            min:
              type: number
              format: decimal
              description: Lowest value of transaction set.
            max:
              type: number
              format: decimal
              description: Highest value of transaction set.
            currency:
              $ref: '#/components/schemas/SourceAccount/properties/currency'
        dataIntegrityDates:
          type: object
          description: Only returned for transactions. For accounts, there is nothing returned.
          properties:
            minDate:
              $ref: '#/components/schemas/DateTime'
              description: Earliest date of transaction set.
              readOnly: true
            maxDate:
              $ref: '#/components/schemas/DateTime'
              description: Latest date of transaction set.
              readOnly: true
            minOverlappingDate:
              $ref: '#/components/schemas/DateTime'
              description: Earliest date where transactions exist in both accounting and banking platforms.
              readOnly: true
            maxOverlappingDate:
              $ref: '#/components/schemas/DateTime'
              description: Latest date where transactions exist in both account and banking platforms.
              readOnly: true
        integrityStatus:
          type: string
          enum:
          - Unknown
          - DoesNotExist
          - Error
          - Complete
          description: The current status of the most recently run matching algorithm.
      examples:
      - type: string
        statusInfo:
          lastMatched: '2021-10-24T14:15:22Z'
          currentStatus: Unknown
          statusMessage: string
        connectionIds:
          source:
          - d5a8d1b2-b38a-4e44-8641-548ad43be6bb
          - da8c9f39-8af9-4a98-964b-f1e207942837
          target:
          - 3d7ce25a-c107-44bc-8e0c-36c10bdd14e0
          - a5300eac-01fa-4a77-b5b0-ea0b86a3be69
        amounts:
          min: 130
          max: 2450
          currency: GBP
        dates:
          minDate: '2021-09-17T12:09:33.441Z'
          maxDate: '2021-12-16T12:12:53.441Z'
          minOverlappingDate: '2021-09-30T12:09:13.441Z'
          maxOverlappingDate: '2021-11-27T12:19:33.441Z'
    DataIntegrityDetail:
      title: Data integrity detail
      type: object
      properties:
        id:
          type: string
          description: ID GUID of the transaction.
        type:
          type: string
          description: The data type of the record.
        connectionId:
          type: string
          format: uuid
          description: ID GUID representing the connection of the accounting or banking platform.
          readOnly: true
        date:
          $ref: '#/components/schemas/DateTime'
          description: The date of the transaction.
        description:
          type: string
          description: The transaction description.
        amount:
          type: number
          format: decimal
          description: The transaction value.
        currency:
          $ref: '#/components/schemas/SourceAccount/properties/currency'
          description: The currency of the transaction.
        matches:
          type: array
          items:
            $ref: '#/components/schemas/DataIntegrityDetail/definitions/dataIntegrityMatch'
      definitions:
        dataIntegrityMatch:
          type: object
          properties:
            id:
              type: string
              description: ID GUID of the transaction.
            type:
              type: string
              description: The data type which the data type in the URL has been matched against. For example, if you've matched accountTransactions and banking-transactions, and you call this endpoint with accountTransactions in the URL, this property would be banking-transactions.
            connectionId:
              type: string
              description: ID GUID representing the connection of the accounting or banking platform.
              format: uuid
            date:
              type: string
              description: The date of the transaction.
            description:
              type: string
              description: The transaction description.
            amount:
              type: string
              description: The transaction value.
            currency:
              $ref: '#/components/schemas/SourceAccount/properties/currency'
              description: The currency of the transaction.
    DateTime:
      title: Date time
      type: string
      examples:
      - '2022-10-23T00:00:00Z'
      - '2022-10-23'
      description: "In Codat's data model, dates and times are represented using the <a class=\"external\" href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:\n\n```\n2020-10-08T22:40:50Z\n2021-01-01T00:00:00\n```\n\n\n\nWhen syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:\n\n- Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z`\n- Unqualified local time: `2021-11-15T01:00:00`\n- UTC time offsets: `2021-11-15T01:00:00-05:00`\n\n> Time zones\n> \n> Not all dates from Codat will contain information about time zones.  \n> Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced."
    DataIntegritySummary:
      title: Data integrity summary
      type: object
      allOf:
      - $ref: '#/components/schemas/DataIntegritySummary/definitions/dataIntegrityType'
      - type: object
        properties:
          byAmount:
            $ref: '#/components/schemas/DataIntegritySummary/definitions/dataIntegrityByAmount'
          byCount:
            $ref: '#/components/schemas/DataIntegritySummary/definitions/dataIntegrityByCount'
      definitions:
        dataIntegrityType:
          type: object
          properties:
            type:
              type: string
              description: The data type which the data type in the URL has been matched against. For example, if you've matched accountTransactions and banking-transactions, and you call this endpoint with accountTransactions in the URL, this property would be banking-transactions.
        dataIntegrityByAmount:
          title: Data integrity by amount
          type: object
          properties:
            matchPercentage:
              type: number
              format: decimal
              description: The percentage of the absolute value of transactions of the type specified in the route which have a match.
            unmatched:
              type: number
              format: decimal
              description: The sum of the absolute value of transactions of the type specified in the route which don't have a match.
            matched:
              type: number
              format: decimal
              description: The sum of the absolute value of transactions of the type specified in the route which have a match.
            total:
              type: number
              format: decimal
              description: The total of unmatched and matched.
            currency:
              $ref: '#/components/schemas/SourceAccount/properties/currency'
        dataIntegrityByCount:
          title: Data integrity by count
          type: object
          properties:
            matchPercentage:
              type: number
              format: decimal
              description: The percentage of records of the type specified in the route which have a match.
            unmatched:
              type: number
              format: decimal
              description: The number of records of the type specified in the route which don't have a match.
            matched:
              type: number
              format: decimal
              description: The number of records of the type specified in the route which do have a match.
            total:
              type: number
              format: decimal
              description: The total of unmatched and matched.
    PagingInfo:
      type: object
      title: Pagination information
      x-internal: true
      properties:
        pageNumber:
          type: integer
          description: Current page number.
        pageSize:
          type: integer
          description: Number of items to return in results array.
          maximum: 2000
        totalResults:
          type: integer
          description: Total number of items.
        _links:
          $ref: '#/components/schemas/PagingInfo/definitions/links'
      definitions:
        links:
          title: Hal Links
          type: object
          required:
          - self
          - current
          properties:
            self:
              $ref: '#/components/schemas/PagingInfo/definitions/halRef'
            current:
              $ref: '#/components/schemas/PagingInfo/definitions/halRef'
            next:
              $ref: '#/components/schemas/PagingInfo/definitions/halRef'
            previous:
              $ref: '#/components/schemas/PagingInfo/definitions/halRef'
          examples:
          - self:
              href: /companies
            current:
              href: /companies?page=1&pageSize=10
        halRef:
          title: Hypertext reference
          type: object
          properties:
            href:
              type: string
              format: uri-reference
              description: Uri hypertext reference.
      required:
      - pageNumber
      - pageSize
      - totalResults
      - _links
      examples:
      - pageNumber: 1
        pageSize: 10
        totalResults: 1
        _links:
          self:
            href: /companies/{id}/data/{dataType}
          current:
            href: /companies/{id}/data/{dataType}?page=1&pageSize=10
    DataIntegrityDetails:
      title: Data integrity details
      x-internal: true
      allOf:
      - type: object
        properties:
          results:
            type: array
            items:
              $ref: '#/components/schemas/DataIntegrityDetail'
      - $ref: '#/components/schemas/PagingInfo'
    ErrorMessage:
      title: Error message
      type: object
      x-internal: true
      properties:
        statusCode:
          type: integer
          description: The HTTP status code returned by the error.
        service:
          type: string
          description: Codat's service the returned the error.
        error:
          type: string
          description: A brief description of the error.
        correlationId:
          type: string
          description: Unique identifier used to propagate to all downstream services and determine the source of the error.
        validation:
          $ref: '#/components/schemas/ErrorMessage/definitions/errorValidation'
        canBeRetried:
          type: string
          description: '`True` if the error occurred transiently and can be retried.'
        detailedErrorCode:
          type: integer
          description: Machine readable error code used to automate processes based on the code returned.
      definitions:
        errorValidation:
          title: Validation error
          type: object
          nullable: true
          description: A human-readable object describing validation decisions Codat has made. If an operation has failed because of validation errors, they will be detailed here.
          properties:
            errors:
              type: array
              nullable: true
              items:
                $ref: '#/components/schemas/ErrorMessage/definitions/errorValidationItem'
            warnings:
              type: array
              nullable: true
              items:
                $ref: '#/components/schemas/ErrorMessage/definitions/errorValidationItem'
        errorValidationItem:
          title: Validation error item
          type: object
          properties:
            itemId:
              type: string
              nullable: true
              description: Unique identifier for a validation item.
            message:
              type: string
              nullable: true
              description: A message outlining validation item's issue.
            validatorName:
              type: string
              nullable: true
              description: Name of validator.
    DataIntegritySummaries:
      title: Data integrity summaries
      x-internal: true
      type: object
      properties:
        summaries:
          type: array
          items:
            $ref: '#/components/schemas/DataIntegritySummary'
    DataIntegrityStatuses:
      title: Data integrity statuses
      x-internal: true
      type: object
      properties:
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/DataIntegrityStatus'
    SourceAccount:
      title: Source account (v1)
      type: object
      description: The target bank account in a supported accounting software for ingestion into a bank feed.
      additionalProperties: false
      properties:
        id:
          type: string
          description: Unique ID for the bank account.
        accountName:
          type: string
          nullable: true
          description: The bank account name.
        accountType:
          type: string
          nullable: true
          description: The type of bank account e.g. Credit.
        accountNumber:
          type: string
          nullable: true
          description: The account number.
        sortCode:
          type: string
          nullable: true
          description: The sort code.
        currency:
          title: Currency
          x-internal: true
          type: string
          description: "The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.\n\n## Unknown currencies\n\nIn line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. \n\nThere are only a very small number of edge cases where this currency code is returned by the Codat system."
          format: ISO4217
          examples:
          - GBP
          - USD
          - EUR
        balance:
          type: number
          format: decimal
          nullable: true
          description: The latest balance for the bank account.
        modifiedDate:
          $ref: '#/components/schemas/DateTime'
          nullable: true
          description: The last date the bank account was modified.
        status:
          type: string
          nullable: true
          description: Status of the source account.
          enum:
          - pending
          - connected
          - connecting
          - disconnected
          - unknown
        feedStartDate:
          $ref: '#/components/schemas/DateTime'
          nullable: true
      required:
      - id
      definitions:
        sourceAccountPrototype:
          title: Source account (v1)
          type: object
          properties:
            id:
              $ref: '#/components/schemas/SourceAccount/properties/id'
            accountName:
              $ref: '#/components/schemas/SourceAccount/properties/accountName'
            accountType:
              $ref: '#/components/schemas/SourceAccount/properties/accountType'
            accountNumber:
              $ref: '#/components/schemas/SourceAccount/properties/accountNumber'
            sortCode:
              $ref: '#/components/schemas/SourceAccount/properties/sortCode'
            currency:
              $ref: '#/components/schemas/SourceAccount/properties/currency'
            balance:
              $ref: '#/components/schemas/SourceAccount/properties/balance'
            modifiedDate:
              $ref: '#/components/schemas/SourceAccount/properties/modifiedDate'
          required:
          - id
        sourceAccounts:
          title: Source accounts
          type: array
          items:
            $ref: '#/components/schemas/SourceAccount'
      examples:
      - id: acc-002
        accountName: account-081
        sortCode: '123456'
        accountType: Credit
        accountNumber: '12345670'
        currency: GBP
        balance: 99.99
        modifiedDate: '2023-01-09T14:14:14.1057478Z'
        status: pending
      - id: acc-003
        accountName: account-095
        sortCode: '123456'
        accountType: Credit
        accountNumber: '12345671'
        currency: USD
        balance: 0
        modifiedDate: '2023-01-09T14:14:14.1057478Z'
        status: pending
  responses:
    Unauthorized:
      description: Your API request was not properly authorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Unauthorized:
              value:
                statusCode: 401
                service: PublicApi
                error: Unauthorized
                correlationId: 7eb40d6b415d7bcd99ce658268284056
                canBeRetried: Unknown
                detailedErrorCode: 0
    Malformed-Query:
      description: Your `query` parameter was not correctly formed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Malformed query:
              value:
                statusCode: 400
                service: ClientsApi
                error: Error parsing query - Malformed query.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
            Unresolved property:
              value:
                statusCode: 400
                service: PullApi
                error: Error parsing query - Could not resolve property isCompleted on Dataset
                correlationId: 98457fb9956b7f9b4b2fd4f6e23bb5c8
                canBeRetried: Unknown
                detailedErrorCode: 0
    Payment-Required:
      description: 'An account limit has been exceeded. The type of limit is described in the error property:


        - You have exceeded the 50-company limit that applies to a Free plan. Delete any companies you no longer need and retry the request.

        - The requested sync schedule is not allowed. You requested an hourly sync schedule but this functionality is not included in the Free plan.

        - Your Free account is older than 365 days and has expired. Contact support@codat.io.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Conflict:
              value:
                statusCode: 429
                service: PublicApi
                error: You have exceeded the 50-company limit that applies to a Free plan. We recommend that you delete any companies you no longer need and retry the request.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
    Too-Many-Requests:
      description: Too many requests were made in a given amount of time. Wait a short period and then try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Conflict:
              value:
                statusCode: 429
                service: PublicApi
                error: You have made too many requests in a given amount of time; please retry later.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
    Not-Found:
      description: 'One or more of the resources you referenced could not be found.

        This might be because your company or data connection id is wrong, or was already deleted.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Data connection not found:
              value:
                statusCode: 404
                service: PublicApi
                error: Data connection a22dd66b-564a-4832-9b37-7b3ce4aeb7de not found
                correlationId: 8fa2b5f4794970a4ee73758f612e8df0
                canBeRetried: Unknown
                detailedErrorCode: 0
            Company not found:
              value:
                statusCode: 404
                service: ClientsApi
                error: No company was found with ID 846ed55c-974b-4392-a1f1-87b6fdbf3c5e
                correlationId: 0a40c2f31fc8f992fb88b0853e4166f3
                canBeRetried: Unknown
                detailedErrorCode: 0
            No data available:
              value:
                statusCode: 404
                service: PublicApi
                error: No data available for accounts for ID e5889b459f544926ac5b8e6756df2s
                correlationId: 0a40c2f31fc8f992fb88b0853e4166f3
                canBeRetried: Unknown
                detailedErrorCode: 0
    Internal-Server-Error:
      description: There is a problem with our server. Please try again later.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Conflict:
              value:
                statusCode: 500
                service: PublicApi
                error: There is a problem with our server. Please try again later.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
    Forbidden:
      description: You are using an outdated API key or a key not associated with that resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Conflict:
              value:
                statusCode: 403
                service: PublicApi
                error: You are using an outdated API key or a key not associated with that resource.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
    Service-Unavailable:
      description: The Codat API is temporarily offline for maintenance. Please try again later.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            Conflict:
              value:
                statusCode: 500
                service: PublicApi
                error: The Codat API is temporarily offline for maintenance. Please try again later.
                correlationId: bc997528a9d7abb9161ef45f05d38599
                canBeRetried: Unknown
                detailedErrorCode: 0
  parameters:
    orderBy:
      name: orderBy
      in: query
      required: false
      schema:
        type: string
        example: -modifiedDate
      description: Field to order results by. [Read more](https://docs.codat.io/using-the-api/ordering-results).
    pageSize:
      name: pageSize
      in: query
      schema:
        type: integer
        format: int32
        default: 100
        example: 100
        minimum: 1
        maximum: 5000
      description: Number of records to return in a page. [Read more](https://docs.codat.io/using-the-api/paging).
    query:
      name: query
      in: query
      required: false
      schema:
        type: string
      example: id=e3334455-1aed-4e71-ab43-6bccf12092ee
      description: Codat query string. [Read more](https://docs.codat.io/using-the-api/querying).
    companyId:
      name: companyId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 8a210b68-6988-11ed-a1eb-0242ac120002
        description: Unique identifier for your SMB in Codat.
      description: Unique identifier for a company.
    dataIntegrityDataType:
      name: dataType
      in: path
      required: true
      schema:
        type: string
        enum:
        - banking-accounts
        - banking-transactions
        - bankAccounts
        - accountTransactions
        example: banking-accounts
      description: A key for a Codat data type.
    page:
      name: page
      in: query
      schema:
        type: integer
        format: int32
        minimum: 1
        example: 1
        default: 1
      description: Page number. [Read more](https://docs.codat.io/using-the-api/paging).
  securitySchemes:
    auth_header:
      name: Authorization
      description: The word "Basic" followed by a space and your API key. [API keys](https://docs.codat.io/platform-api#/schemas/ApiKeyDetails) are tokens used to control access to the API. You can get an API key via [the Codat Portal](https://app.codat.io/developers/api-keys), via [the API](https://docs.codat.io/platform-api#/operations/list-api-keys), or [read more](https://docs.codat.io/using-the-api/authentication) about authentication at Codat.
      type: apiKey
      in: header
      x-speakeasy-example: Basic BASE_64_ENCODED(API_KEY)
x-speakeasy-retries:
  strategy: backoff
  backoff:
    initialInterval: 500
    maxInterval: 60000
    maxElapsedTime: 3600000
    exponent: 1.5
  statusCodes:
  - 408
  - 429
  - 5XX
  retryConnectionErrors: true
x-speakeasy-name-override:
- operationId: ^list-.*?
  methodNameOverride: list
- operationId: ^list-.*?-attachments
  methodNameOverride: list-attachments
- operationId: ^get-.*?
  methodNameOverride: get
- operationId: ^get-create-.*?-model
  methodNameOverride: get-create-model
- operationId: ^get-create-update.*?-model
  methodNameOverride: get-create-update-model
- operationId: ^get-.*?-attachment
  methodNameOverride: get-attachment
- operationId: ^update-.*?
  methodNameOverride: update
- operationId: ^create-.*?
  methodNameOverride: create
- operationId: ^delete-.*?
  methodNameOverride: delete
- operationId: ^delete-.*?-attachment
  methodNameOverride: delete-attachment
- operationId: ^download-.*?-attachment
  methodNameOverride: download-attachment
- operationId: ^upload-.*?-attachment
  methodNameOverride: upload-attachment
x-codat-docs-path: bank-feeds-api
x-codat-keep-docs-paths-local: true
x-codat-speakeasy-pagination:
  type: offsetLimit
  inputs:
  - name: page
    in: parameters
    type: page
  outputs:
    results: $.results
